[programs.devnet]
example_sol_anchor_contract = "BM8eAdE2JbN4HL2vPaZnbsxGH6TTVi11jFbz8t79hXKw"

[provider]
cluster = "devnet"
wallet = "/home/yunhao/pyth/wallet/pair.json"

[scripts]
install = "npm i chai mocha ts-mocha @types/bn.js @types/chai @types/mocha typescript prettier @project-serum/anchor"
invoke = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/invoke.ts"
