name: Pyth SDK Example Terra Contract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/terra-contract
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true

      - name: Compile WASM contract
        run: cargo build --release --target wasm32-unknown-unknown
        env:
          RUSTFLAGS: "-C link-arg=-s"

  lints:
    name: Lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/terra-contract
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          override: true
          components: clippy

      - name: Generate Schema
        run: cargo run --example schema

      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
