# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Pyth SDK Example Terra Contract

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/terra-contract
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true
      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

  lints:
    name: Lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/terra-contract
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          override: true
          components: clippy

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked

      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
